name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger on push to 'main' branch

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest  # The OS the workflow will run on
    
    steps:
      # Step 1: Check out the repository's code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up GitHub Pages for deployment
      - name: Setup Pages
        uses: actions/configure-pages@v5

      # Step 3: Upload the files for deployment
      - name: Upload site
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public  # Change this to the directory where your site files (index.html) are located (e.g., ./dist or ./public)

      # Step 4: Deploy the uploaded files to GitHub Pages
      - name: Deploy site
        uses: actions/deploy-pages@v4

