name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # This runs the action whenever there’s a push to the 'main' branch

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest  # The OS the workflow will run on
    
    steps:
      # Step 1: Check out the repository's code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up GitHub Pages for deployment
      - name: Setup Pages
        uses: actions/configure-pages@v5

      # Step 3: Upload the files for deployment (root of your project)
      - name: Upload site
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./  # Upload files from the root directory

      # Step 4: Deploy the uploaded files to GitHub Pages
      - name: Deploy site
        uses: actions/deploy-pages@v4
